steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build an image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/asya-kawai/ocaml_micro_services:$COMMIT_SHA', '.']
    dir: 'first_arch'
    timeout: 1800s

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to container registry'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/asya-kawai/ocaml_micro_services:$COMMIT_SHA']
    dir: 'first_arch'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Overwrite manifest to update container image for development'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        set -x && \
        ls -la && \
        sed -i -e 's/__COMMIT_SHA__/${SHORT_SHA}/g' -e 's/__PROJECT_ID__/${PROJECT_ID}/g' manifests/dev.yaml
    dir: 'micro-service-arch'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply manifest for development'
    args: ['apply', '-f', 'manifests/dev.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=micro-service-demo'
    dir: 'micro-service-arch'

timeout: 3600s
