# Note:
# '__COMMIT_SHA__' and '__PROJECT_ID__' are replaced in CloudBuild step.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user
        app.kubernetes.io/instance: user-__COMMIT_SHA__
        app.kubernetes.io/version: __COMMIT_SHA__
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: self
        app.kubernetes.io/managed-by: manual
    spec:
      containers:
        - name: ocaml-first-arch
        - image: gcr.io/__PROJECT_ID__/github.com/asya-kawai/ocaml_micro_services:__COMMIT_SHA__
          ports:
            - containerPort: 3000
